### ISSUE TITLE
Unable to locate element: [id="consumer_user_nav"]

### ISSUE THREAD

**Issue by OdinGitDat** [StegSchreck/RatS#100]
When importing from imdb.

- Version: commit fcaa3f8c78b92f9ff0ed3d87bc74139e5788474b
- Platform OS: UbuntuLTS 18
- Running in a virtualenv?: LXC
- Running in Docker?: yes
- Executed command: `docker run -it -v ~/.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source imdb --destination trakt`

## Stacktrace
```
===== IMDB: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 176, in <module>
    main()
  File "transfer_ratings.py", line 73, in main
    execute(args)
  File "transfer_ratings.py", line 118, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/RatS/RatS/imdb/imdb_ratings_parser.py", line 10, in __init__
    super(IMDBRatingsParser, self).__init__(IMDB(args), args)
  File "/RatS/RatS/imdb/imdb_site.py", line 28, in __init__
    raise e
  File "/RatS/RatS/imdb/imdb_site.py", line 24, in __init__
    self._get_ratings_url()
  File "/RatS/RatS/imdb/imdb_site.py", line 44, in _get_ratings_url
    account_link = self.browser.find_element_by_id('consumer_user_nav').find_element_by_tag_name('a') \
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="consumer_user_nav"]

```

**Comment by Hyphen-ated** [comment]
I get the same problem when trying to import to IMDB
