### ISSUE TITLE
Inserting into IMDB fails

### ISSUE THREAD

**Issue by pedrojvaz** [StegSchreck/RatS#110]
**Describe the bug**
I'm using Trakt to IMDB and it fails with an error

**To Reproduce**
Execute the command. It fails every time 

**Expected behavior**

**Desktop (please complete the following information):**
- Version: 9608b1436ec51968905f17589959a701e1afe5e0
- Platform OS: Ubuntu 18.04.4 LTS (bionic)
- Firefox version: 74.0b9 (64-bit) 
- Geckodriver version: geckodriver 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)
- Python version: Python 3.6.9
- PIP version:  pip 19.2.3 from /home/vaz/.local/lib/python3.6/site-packages/pip (python 3.6)
- Running in a virtualenv?: No
- Running in Docker?:No
- Executed command: sudo -H python3 transfer_ratings.py --source trakt --destination imdb --file 20200302224956_Trakt.json

## Stacktrace
```
<!--
===== Trakt: performing login^[[B
===== loaded 1723 movies from /opt/RatS/RatS/exports/20200302224956_Trakt.json
===== IMDB: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 227, in <module>
    main()
  File "transfer_ratings.py", line 79, in main
    execute(args)
  File "transfer_ratings.py", line 129, in execute
    execute_inserting(args, movies, parser)
  File "transfer_ratings.py", line 146, in execute_inserting
    inserter = get_inserter_from_arg(destination)(args)
  File "/opt/RatS/RatS/imdb/imdb_ratings_inserter.py", line 15, in __init__
    super(IMDBRatingsInserter, self).__init__(IMDB(args), args)
  File "/opt/RatS/RatS/imdb/imdb_site.py", line 19, in __init__
    self.USERID = self.browser.find_element_by_id('main').get_attribute('data-userid')
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="main"]
-->
```

## Geckodriver log
```
<!--
1583185797208   addons.webextension.doh-rollout@mozilla.org     WARN    Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1583185797254   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1583185797254   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1583185797255   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1583185797255   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1583185800399   Marionette      WARN    TLS certificate errors will be ignored for this session
1583192653000   addons.webextension.doh-rollout@mozilla.org     WARN    Loading extension 'doh-rollout@mozilla.org': Reading manifest: Invalid extension permission: networkStatus
1583192653052   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1583192653052   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: telemetry
1583192653053   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1583192653053   addons.webextension.screenshots@mozilla.org     WARN    Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
1583192656513   Marionette      WARN    TLS certificate errors will be ignored for this session
-->
```

**Additional context**

**Comment by mraniki** [comment]
Encountering the same issue
