### ISSUE TITLE
error while running with Rotten Tomatoes source

### ISSUE THREAD

**Issue by miko-moshe** [StegSchreck/RatS#122]
Hi, I get this error when running with source Rotten Tomatoes:

# python3 transfer_ratings.py -x --source rottentomatoes --destination imdb

===== RottenTomatoes: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 227, in <module>
    main()
  File "transfer_ratings.py", line 79, in main
    execute(args)
  File "transfer_ratings.py", line 127, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/root/RatS/RatS/rottentomatoes/rottentomatoes_ratings_parser.py", line 9, in __init__
    super(RottenTomatoesRatingsParser, self).__init__(RottenTomatoes(args), args)
  File "/root/RatS/RatS/rottentomatoes/rottentomatoes_site.py", line 12, in __init__
    super(RottenTomatoes, self).__init__(args)
  File "/root/RatS/RatS/base/base_site.py", line 35, in __init__
    self._init_browser()
  File "/root/RatS/RatS/base/base_site.py", line 68, in _init_browser
    self.login()
  File "/root/RatS/RatS/base/base_site.py", line 76, in login
    self._pre_login_action()
  File "/root/RatS/RatS/rottentomatoes/rottentomatoes_site.py", line 23, in _pre_login_action
    self.browser.execute_script("return $.find('#header-top-bar-login')[0].click()")
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: $.find(...)[0] is undefined

**Desktop (please complete the following information):**
- Version: 0.12.1
- Platform OS: CentOS 7
- Firefox version: 78.0.2
- Geckodriver version: 0.26.0
- Python version:3.6.8
- PIP version: 9.0.3
- Running in a virtualenv?: VirtualBox Centos guest on Windows host
- Running in Docker?: no
- Executed command: python3 transfer_ratings.py -x --source rottentomatoes --destination imdb
`

## Geckodriver log
```
JavaScript error: resource://gre/modules/URIFixup.jsm, line 281: NS_ERROR_FAILURE: Should pass a non-null uri

**Comment by StegSchreck** [comment]
Hey @miko-moshe 
Thanks for bringing this to my attention. RottenTomatoes seems to have changed its markup (re-implementation?). I adapted the code accordingly. Hope you can use this now :)

**Comment by miko-moshe** [comment]
@StegSchreck  works great now. Thanks!
