### ISSUE TITLE
Trakt: Unable to locate element: .summary-user-rating

### ISSUE THREAD

**Issue by OdinGitDat** [StegSchreck/RatS#140]
- Version: 9b549c71e2c07587f91b8834f9d7af4145b5da9c
- Running in Docker?: yes
- Executed command: `docker run --rm -it -v ~/.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats:master python3 transfer_ratings.py --source imdb --destination trakt`

## Stacktrace
```
===== IMDB: CSV downloaded to /RatS/RatS/exports/20201017200533_IMDB.csv
===== getting movies from CSV

===== IMDB: saved 605 parsed movies to /RatS/RatS/exports/20201017200533_IMDB.json
===== Trakt: posting 605 movies
  2% (15 of 605) |#                                                              | Elapsed Time: 0:02:02 ETA:   1:40:03
ERROR: There was an exception inside Trakt (see below). Skipping insertion.

===== ABORTING =====
  2% (15 of 605) |#                                                              | Elapsed Time: 0:03:06 ETA:  12:17:04
Traceback (most recent call last):
  File "transfer_ratings.py", line 216, in insert_movie_ratings
    inserter.insert(movies, source)
  File "/RatS/RatS/base/base_ratings_inserter.py", line 44, in insert
    self._post_movie_rating(movie[source.lower()]['my_rating'])
  File "/RatS/RatS/base/base_ratings_inserter.py", line 146, in _post_movie_rating
    raise e
  File "/RatS/RatS/base/base_ratings_inserter.py", line 141, in _post_movie_rating
    self._click_rating(my_rating)
  File "/RatS/RatS/trakt/trakt_ratings_inserter.py", line 59, in _click_rating
    user_rating_section = self.site.browser.find_element_by_class_name('summary-user-rating')
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .summary-user-rating
```

**Comment by StegSchreck** [comment]
becomes obsolete with #306
