### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="main"]

### ISSUE THREAD

**Issue by techdough** [StegSchreck/RatS#157]
docker run -it -v ~/.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source trakt --all-destinations --verbose

===== IMDB: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 227, in <module>
    main()
  File "transfer_ratings.py", line 79, in main
    execute(args)
  File "transfer_ratings.py", line 129, in execute
    execute_inserting(args, movies, parser)
  File "transfer_ratings.py", line 146, in execute_inserting
    inserter = get_inserter_from_arg(destination)(args)
  File "/RatS/RatS/imdb/imdb_ratings_inserter.py", line 15, in __init__
    super(IMDBRatingsInserter, self).__init__(IMDB(args), args)
  File "/RatS/RatS/imdb/imdb_site.py", line 19, in __init__
    self.USERID = self.browser.find_element_by_id('main').get_attribute('data-userid')
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="main"]

**Comment by keldian** [comment]
Same here with `docker run -d -v /opt/RatS/credentials.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source trakt --destination imdb`

**Comment by dominikrys** [comment]
I'm experiencing the same issue using the same issue when running `docker run -it -v ~/.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source trakt --destination imdb`. Has anyone found a solution?
