### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'max_value' (progressbar?) - debian WSL

### ISSUE THREAD

**Issue by noyse27** [StegSchreck/RatS#175]
seems to be a problem with the progressbar.
i'm using 

`python3-progressbar is already the newest version (2.5-2)`

```
noyse27@MSI:~/RatS$ sudo python3 transfer_ratings.py --source trakt --destination letterboxd
===== Trakt: Parsing 12 pages with 661 movies in total
Traceback (most recent call last):
  File "/home/noyse27/RatS/transfer_ratings.py", line 271, in <module>
    main()
  File "/home/noyse27/RatS/transfer_ratings.py", line 92, in main
    execute(args)
  File "/home/noyse27/RatS/transfer_ratings.py", line 169, in execute
    movies = execute_parsing(args, parser)
  File "/home/noyse27/RatS/transfer_ratings.py", line 217, in execute_parsing
    movies = parse_data_from_source(parser)
  File "/home/noyse27/RatS/transfer_ratings.py", line 223, in parse_data_from_source
    movies = parser.parse()
  File "/home/noyse27/RatS/RatS/base/base_ratings_parser.py", line 36, in parse
    self._parse_ratings()
  File "/home/noyse27/RatS/RatS/base/base_ratings_parser.py", line 79, in _parse_ratings
    self._parse_movie_listing_page(movie_listing_page)
  File "/home/noyse27/RatS/RatS/base/base_ratings_parser.py", line 103, in _parse_movie_listing_page
    self.print_progress(movie)
  File "/home/noyse27/RatS/RatS/base/base_ratings_parser.py", line 118, in print_progress
    self._print_progress_bar()
  File "/home/noyse27/RatS/RatS/base/base_ratings_parser.py", line 122, in _print_progress_bar
    self.progress_bar = ProgressBar(
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

**Comment by StegSchreck** [comment]
Have you installed progressbar separately using `apt` or did you install that version via `pip install -r requirements.txt`?

For me it looks like this:
![image](https://user-images.githubusercontent.com/9078002/142928084-72be8f18-5f36-47d5-a36c-cb6cf61f2f45.png)

**Comment by noyse27** [comment]
hi
first i did "`pip install -r requirements.tx`t"
then i've got

```
noyse@MSI:~/RatS$ sudo python3 transfer_ratings.py --source trakt --destination letterboxd
Traceback (most recent call last):
  File "/home/noyse/RatS/transfer_ratings.py", line 9, in <module>
    from RatS.allocine.allocine_ratings_inserter import AlloCineRatingsInserter
  File "/home/noyse/RatS/RatS/allocine/allocine_ratings_inserter.py", line 8, in <module>
    from RatS.base.base_ratings_inserter import RatingsInserter
  File "/home/noyse/RatS/RatS/base/base_ratings_inserter.py", line 6, in <module>
    from progressbar import ProgressBar
ModuleNotFoundError: No module named 'progressbar'

```
after that i did "`pip install -r requirements.txt`" again and it said that progressbar is already installed:

```
noyse@MSI:~/RatS$ pip install -r requirements.txt
Requirement already satisfied: beautifulsoup4==4.10.0 in /home/noyse/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (4.10.0)
Requirement already satisfied: bs4==0.0.1 in /home/noyse/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: configparser==5.1.0 in /home/noyse/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (5.1.0)
Requirement already satisfied: progressbar2==3.55.0 in /home/noyse/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (3.55.0)
Requirement already satisfied: selenium==4.0.0 in /home/noyse/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (4.0.0)
Requirement already satisfied: xvfbwrapper==0.2.9 in /home/noyse/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (0.2.9)
Requirement already satisfied: black in /home/noyse/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (21.11b1)
Requirement already satisfied: soupsieve>1.2 in /home/noyse/.local/lib/python3.9/site-packages (from beautifulsoup4==4.10.0->-r requirements.txt (line 1)) (2.3.1)
Requirement already satisfied: six in /home/noyse/.local/lib/python3.9/site-packages (from progressbar2==3.55.0->-r requirements.txt (line 4)) (1.16.0)
Requirement already satisfied: python-utils>=2.3.0 in /home/noyse/.local/lib/python3.9/site-packages (from progressbar2==3.55.0->-r requirements.txt (line 4)) (2.5.6)
Requirement already satisfied: trio-websocket~=0.9 in /home/noyse/.local/lib/python3.9/site-packages (from selenium==4.0.0->-r requirements.txt (line 5)) (0.9.2)
Requirement already satisfied: trio~=0.17 in /home/noyse/.local/lib/python3.9/site-packages (from selenium==4.0.0->-r requirements.txt (line 5)) (0.19.0)
Requirement already satisfied: urllib3[secure]~=1.26 in /home/noyse/.local/lib/python3.9/site-packages (from selenium==4.0.0->-r requirements.txt (line 5)) (1.26.7)
Requirement already satisfied: sortedcontainers in /home/noyse/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.0.0->-r requirements.txt (line 5)) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in /home/noyse/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.0.0->-r requirements.txt (line 5)) (1.10)
Requirement already satisfied: outcome in /home/noyse/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.0.0->-r requirements.txt (line 5)) (1.1.0)
Requirement already satisfied: idna in /home/noyse/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.0.0->-r requirements.txt (line 5)) (3.3)
Requirement already satisfied: attrs>=19.2.0 in /home/noyse/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.0.0->-r requirements.txt (line 5)) (21.2.0)
Requirement already satisfied: sniffio in /home/noyse/.local/lib/python3.9/site-packages (from trio~=0.17->selenium==4.0.0->-r requirements.txt (line 5)) (1.2.0)
Requirement already satisfied: wsproto>=0.14 in /home/noyse/.local/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium==4.0.0->-r requirements.txt (line 5)) (1.0.0)
Requirement already satisfied: certifi in /home/noyse/.local/lib/python3.9/site-packages (from urllib3[secure]~=1.26->selenium==4.0.0->-r requirements.txt (line 5)) (2021.10.8)
Requirement already satisfied: pyOpenSSL>=0.14 in /home/noyse/.local/lib/python3.9/site-packages (from urllib3[secure]~=1.26->selenium==4.0.0->-r requirements.txt (line 5)) (21.0.0)
Requirement already satisfied: cryptography>=1.3.4 in /home/noyse/.local/lib/python3.9/site-packages (from urllib3[secure]~=1.26->selenium==4.0.0->-r requirements.txt (line 5)) (35.0.0)
Requirement already satisfied: cffi>=1.12 in /home/noyse/.local/lib/python3.9/site-packages (from cryptography>=1.3.4->urllib3[secure]~=1.26->selenium==4.0.0->-r requirements.txt (line 5)) (1.15.0)
Requirement already satisfied: pycparser in /home/noyse/.local/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=1.3.4->urllib3[secure]~=1.26->selenium==4.0.0->-r requirements.txt (line 5)) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in /home/noyse/.local/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.0.0->-r requirements.txt (line 5)) (0.12.0)
Requirement already satisfied: tomli<2.0.0,>=0.2.6 in /home/noyse/.local/lib/python3.9/site-packages (from black->-r requirements.txt (line 7)) (1.2.2)
Requirement already satisfied: mypy-extensions>=0.4.3 in /home/noyse/.local/lib/python3.9/site-packages (from black->-r requirements.txt (line 7)) (0.4.3)
Requirement already satisfied: regex>=2021.4.4 in /home/noyse/.local/lib/python3.9/site-packages (from black->-r requirements.txt (line 7)) (2021.11.10)
Requirement already satisfied: typing-extensions>=3.10.0.0 in /home/noyse/.local/lib/python3.9/site-packages (from black->-r requirements.txt (line 7)) (4.0.0)
Requirement already satisfied: pathspec<1,>=0.9.0 in /home/noyse/.local/lib/python3.9/site-packages (from black->-r requirements.txt (line 7)) (0.9.0)
Requirement already satisfied: click>=7.1.2 in /home/noyse/.local/lib/python3.9/site-packages (from black->-r requirements.txt (line 7)) (8.0.3)
Requirement already satisfied: platformdirs>=2 in /home/noyse/.local/lib/python3.9/site-packages (from black->-r requirements.txt (line 7)) (2.4.0)
```

the i installed it with `sudo apt-get install python3-progressbar`
after that i've got the error message with the `max_value`

**Comment by noyse27** [comment]
okay now it works

```
noyse@MSI:~/RatS$ sudo pip3 install progressbar2
Collecting progressbar2
  Downloading progressbar2-3.55.0-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from progressbar2) (1.16.0)
Collecting python-utils>=2.3.0
  Downloading python_utils-2.5.6-py2.py3-none-any.whl (12 kB)
Installing collected packages: python-utils, progressbar2
Successfully installed progressbar2-3.55.0 python-utils-2.5.6
noyse@MSI:~/RatS$ sudo python3 transfer_ratings.py --source trakt --destination letterboxd
===== Trakt: Parsing 12 pages with 662 movies in total
  5% (35 of 662) |###                                                            | Elapsed Time: 0:01:28 ETA:   0:26:11
```
