### ISSUE TITLE
Crash when moving ratings from Trakt to IMDB

### ISSUE THREAD

**Issue by pedrojvaz** [StegSchreck/RatS#179]
**Describe the bug**
Crashes with python error
`AttributeError: 'NoneType' object has no attribute 'find'`

**To Reproduce**
1. Start with `python3 transfer_ratings.py --source trakt --destination imdb`
1. Error: crashes after a while

**Expected behavior**
Complete succesfully

**Desktop (please complete the following information):**
- Version: `f306be6`
- Platform OS: `Ubuntu 21.04`
- Firefox version: `Mozilla Firefox 94.0`
- Geckodriver version: `0.28.0` (c00d2b6acd3f 2020-11-03 16:29 +0200)
- Python version: `3.9.5`
- PIP version: `20.3.4`
- Running in a virtualenv?: no
- Running in Docker?:  no
- Executed command: `python3 transfer_ratings.py --source trakt --destination imdb`

## Stacktrace
```
===== Trakt: Parsing 31 pages with 1844 movies in total
 54% (1013 of 1844) |###############################################                                        | Elapsed Time: 1:16:36 ETA:   1:10:25Traceback (most recent call last):
  File "/opt/RatS/transfer_ratings.py", line 271, in <module>
    main()
  File "/opt/RatS/transfer_ratings.py", line 92, in main
    execute(args)
  File "/opt/RatS/transfer_ratings.py", line 169, in execute
    movies = execute_parsing(args, parser)
  File "/opt/RatS/transfer_ratings.py", line 217, in execute_parsing
    movies = parse_data_from_source(parser)
  File "/opt/RatS/transfer_ratings.py", line 223, in parse_data_from_source
    movies = parser.parse()
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 40, in parse
    raise e
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 36, in parse
    self._parse_ratings()
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 51, in _parse_ratings
    pages_count = self._retrieve_pages_count_and_movies_count(movie_ratings_page)
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 83, in _retrieve_pages_count_and_movies_count
    self.movies_count = self._get_movies_count(movie_ratings_page)
  File "/opt/RatS/RatS/trakt/trakt_ratings_parser.py", line 17, in _get_movies_count
    movie_ratings_page.find("section", class_="subnav-wrapper")
AttributeError: 'NoneType' object has no attribute 'find'
```

## Geckodriver log
```
1637965056191	geckodriver	INFO	Listening on 127.0.0.1:44813
1637965057370	Marionette	INFO	Marionette enabled
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofilezUAwbH/search.json.mozlz4", (void 0)))
1637965059761	Marionette	INFO	Listening on port 41275
1637965059844	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
JavaScript error: https://trakt.tv/assets/application-f3510f6635f646e5da6771ce714ba404198339541a146a8306ad6c05c8da032b.js, line 1761: ReferenceError: grecaptcha is not defined
ATTENTION: default value of option mesa_glthread overridden by environment.
JavaScript warning: https://pagead2.googlesyndication.com/bg/CRtE2hXI-Oo2CzbqEvynNThBTGvKRH_6so9ly1Scye0.js line 1 > eval line 4962 > eval line 1 > eval line 1 > eval, line 1: WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER.
ATTENTION: default value of option mesa_glthread overridden by environment.
JavaScript warning: https://pagead2.googlesyndication.com/bg/CRtE2hXI-Oo2CzbqEvynNThBTGvKRH_6so9ly1Scye0.js line 1 > eval line 2448 > eval line 1 > eval line 1 > eval, line 1: WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER.
JavaScript warning: https://pagead2.googlesyndication.com/bg/CRtE2hXI-Oo2CzbqEvynNThBTGvKRH_6so9ly1Scye0.js line 1 > eval line 1361 > eval line 1 > eval line 1 > eval, line 1: WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER.
JavaScript warning: https://pagead2.googlesyndication.com/bg/CRtE2hXI-Oo2CzbqEvynNThBTGvKRH_6so9ly1Scye0.js line 1 > eval line 659 > eval line 1 > eval line 1 > eval, line 1: WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER.

#it goes on and on...

```

**Additional context**

**Comment by noyse27** [comment]
i had this error too but after 3 times of restarting it worked as expected ( the trakt parsing)

**Comment by StegSchreck** [comment]
becomes obsolete with #306
