### ISSUE TITLE
OSError: Can not find Xvfb.

### ISSUE THREAD

**Issue by wisdomtooth** [StegSchreck/RatS#187]
**Describe the bug**
I understand Windows is not supported, but still... I got past the [fcntl issue,](https://github.com/StegSchreck/RatS/issues/105) but got bogged down on this one.

**To Reproduce**
Run `transfer_ratings.py` on Windows PowerShell or Ubuntu for Windows.

**Expected behavior**
Successful run.

**Desktop (please complete the following information):**
- Version: 0.13
- Platform OS: Windows 10 Home
- Firefox version: 98.0.2 (64-bit)
- Geckodriver version: 0.30.0
- Python version: 3.8.10, 3.10.4
- PIP version: 22.0.4
- Running in a virtualenv?: no
- Running in Docker?: no
- Executed command: `python3 transfer_ratings.py -s trakt -d imdb`

## Stacktrace
```/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "transfer_ratings.py", line 271, in <module>
    main()
  File "transfer_ratings.py", line 92, in main
    execute(args)
  File "transfer_ratings.py", line 168, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/home/andre/RatS/RatS/imdb/imdb_ratings_parser.py", line 10, in __init__
    super(IMDBRatingsParser, self).__init__(IMDB(args), args)
  File "/home/andre/RatS/RatS/imdb/imdb_site.py", line 15, in __init__
    super(IMDB, self).__init__(args)
  File "/home/andre/RatS/RatS/base/base_site.py", line 41, in __init__
    self._init_browser()
  File "/home/andre/RatS/RatS/base/base_site.py", line 80, in _init_browser
    self.browser_handler = BrowserHandler(self.args)
  File "/home/andre/RatS/RatS/utils/browser_handler.py", line 20, in __init__
    self.display = Xvfb()
  File "/home/andre/.local/lib/python3.8/site-packages/xvfbwrapper.py", line 41, in __init__
    raise EnvironmentError(msg)
OSError: Can not find Xvfb. Please install it and try again.```

**Comment by wisdomtooth** [comment]
Silly me; sorted: `sudo apt-get install xvfb`.

**Comment by WhoMI7** [comment]
@wisdomtooth  can you write a somewhat detailed way to use it on windows, if possible? 😅
I keep running into a lot of issues for some reason
