### ISSUE TITLE
Docker solution not working on Windows 10

### ISSUE THREAD

**Issue by StegSchreck** [StegSchreck/RatS#19]
reported by: @michomuchomacho:

I tried to import (with docker) to imdb and tmdb but got these errors: 

TRAKT TO TMDB:  `docker run -it -v /.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source trakt --destination imdb`
```
===== Trakt: Parsing 1 pages with 0 movies in total
===== Trakt: Parsing 1 pages with 0 movies in total 
Traceback (most recent call last): File "/RatS/RatS/base/base_ratings_parser.py", line 21, in parse self._parse_ratings() File "/RatS/RatS/base/base_ratings_parser.py", line 42, in _parse_ratings self._parse_movie_listing_page(movie_listing_page) File "/RatS/RatS/base/base_ratings_parser.py", line 56, in _parse_movie_listing_page movies_tiles = self._get_movie_tiles(movie_listing_page) File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 30, in _get_movie_tiles return movie_listing_page.find(class_='row posters').find_all('div', attrs={'data-type': 'movie'}) AttributeError: 'NoneType' object has no attribute 'find_all' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "transfer_ratings.py", line 125, in <module> main() File "transfer_ratings.py", line 56, in main execute(args) File "transfer_ratings.py", line 95, in execute movies = parse_data_from_source(parser) File "transfer_ratings.py", line 104, in parse_data_from_source movies = parser.parse() File "/RatS/RatS/base/base_ratings_parser.py", line 24, in parse self._parse_ratings() File "/RatS/RatS/base/base_ratings_parser.py", line 42, in _parse_ratings self._parse_movie_listing_page(movie_listing_page) File "/RatS/RatS/base/base_ratings_parser.py", line 56, in _parse_movie_listing_page movies_tiles = self._get_movie_tiles(movie_listing_page) File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 30, in _get_movie_tiles return movie_listing_page.find(class_='row posters').find_all('div', attrs={'data-type': 'movie'}) AttributeError: 'NoneType' object has no attribute 'find_all'
```
TRAKT TO TMDB:  `docker run -it -v /.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source trakt --destination tmdb`
```
===== Trakt: Parsing 1 pages with 0 movies in total 
===== Trakt: Parsing 1 pages with 0 movies in total 
Traceback (most recent call last): File "/RatS/RatS/base/base_ratings_parser.py", line 21, in parse self._parse_ratings() File "/RatS/RatS/base/base_ratings_parser.py", line 42, in _parse_ratings self._parse_movie_listing_page(movie_listing_page) File "/RatS/RatS/base/base_ratings_parser.py", line 56, in _parse_movie_listing_page movies_tiles = self._get_movie_tiles(movie_listing_page) File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 30, in _get_movie_tiles return movie_listing_page.find(class_='row posters').find_all('div', attrs={'data-type': 'movie'}) AttributeError: 'NoneType' object has no attribute 'find_all' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "transfer_ratings.py", line 125, in <module> main() File "transfer_ratings.py", line 56, in main execute(args) File "transfer_ratings.py", line 95, in execute movies = parse_data_from_source(parser) File "transfer_ratings.py", line 104, in parse_data_from_source movies = parser.parse() File "/RatS/RatS/base/base_ratings_parser.py", line 24, in parse self._parse_ratings() File "/RatS/RatS/base/base_ratings_parser.py", line 42, in _parse_ratings self._parse_movie_listing_page(movie_listing_page) File "/RatS/RatS/base/base_ratings_parser.py", line 56, in _parse_movie_listing_page movies_tiles = self._get_movie_tiles(movie_listing_page) File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 30, in _get_movie_tiles return movie_listing_page.find(class_='row posters').find_all('div', attrs={'data-type': 'movie'}) AttributeError: 'NoneType' object has no attribute 'find_all' 
```

**Comment by StegSchreck** [comment]
The riddle of the 0 movies to be parsed seems to be solved. The -v option for the docker  command doesn't seem to work as in Linux. 

After circumventing that, the following error remains:
```
===== Trakt: performing loginTraceback (most recent call last):                   File "/RatS/RatS/base/base_ratings_parser.py", line 21, in parse                  self._parse_ratings()                                                         File "/RatS/RatS/base/base_ratings_parser.py", line 33, in _parse_ratings         self.movies_count = self._get_movies_count(movie_ratings_page)                File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 16, in _get_movies_count    return int(movie_ratings_page.find('section', class_='subnav-wrapper').     AttributeError: 'NoneType' object has no attribute 'find'                                                                                                       During handling of the above exception, another exception occurred:                                                                                             Traceback (most recent call last):                                                File "transfer_ratings.py", line 125, in <module>                                 main()                                                                        File "transfer_ratings.py", line 56, in main                                      execute(args)                                                                 File "transfer_ratings.py", line 95, in execute                                   movies = parse_data_from_source(parser)                                       File "transfer_ratings.py", line 104, in parse_data_from_source                   movies = parser.parse()                                                       File "/RatS/RatS/base/base_ratings_parser.py", line 24, in parse                  self._parse_ratings()                                                         File "/RatS/RatS/base/base_ratings_parser.py", line 33, in _parse_ratings         self.movies_count = self._get_movies_count(movie_ratings_page)                File "/RatS/RatS/trakt/trakt_ratings_parser.py", line 16, in _get_movies_count    return int(movie_ratings_page.find('section', class_='subnav-wrapper').     AttributeError: 'NoneType' object has no attribute 'find'                       
```

**Comment by StegSchreck** [comment]
abandoned. Please use linux :P

**Comment by hairyhippy** [comment]
So this will never work in Docker for Windows?

**Comment by StegSchreck** [comment]
> So this will never work in Docker for Windows?

Sorry, but I have no Windows system anymore that I could use for debugging this issue anymore. As far as I heard, the [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) actually behaves quite similar to a real linux, so I would recommend using that for now.

**Comment by hairyhippy** [comment]
Great - Thank you, I'll give it a try!

**Comment by hairyhippy** [comment]
All was going swimmingly well considering I have never used either WSL or Linux until when running the script it got to the IMDB login and said failed due to needing a Captcha challenge...  Trakt login and parsing worked like a dream however :-)

ERROR: Login to IMDB failed.
There seems to be a Captcha challenge present for the login.  Please try again later.

I, therefore, logged into IMDB using Chrome in Windows and it never asked Captcha.  I wonder if it's a "1st time" login via Linux issue?
