### ISSUE TITLE
LetterBoxd Parser: signin element could not be scrolled into view

### ISSUE THREAD

**Issue by nicoferfio** [StegSchreck/RatS#195]
**Describe the bug**
The signin element of the letterboxd parser cannot be scrolled into view

**To Reproduce**
Run python3 transfer_ratings.py --source letterboxd --destination filmaffinity

**Expected behavior**
Parser parses LetterBoxd and output is shown in console

**Desktop (please complete the following information):**
- Version: `e58eb890e1f8d0e83fc6fe0db86836627e7dda15` 
- Platform OS: `WSL 2 Ubuntu 20.04 running on Windows 11 Pro Insider Preview Version 22H2 OS build 25179.1000` 
- Firefox version: `103.0 (64-bit)`
- Geckodriver version: `geckodriver 0.31.0`
- Python version: `Python 3.8.10` 
- PIP version: `pip 20.0.2` 
- Running in a virtualenv?: yes 
- Running in Docker?: no 
- Executed command: `python3 transfer_ratings.py --source letterboxd --destination filmaffinity` 

## Stacktrace
```
<!--
===== Letterboxd: performing login/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.11) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "transfer_ratings.py", line 271, in <module>
    main()
  File "transfer_ratings.py", line 92, in main
    execute(args)
  File "transfer_ratings.py", line 168, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/home/nicoferfio/rats/RatS/RatS/letterboxd/letterboxd_ratings_parser.py", line 11, in __init__
    super(LetterboxdRatingsParser, self).__init__(Letterboxd(args), args)
  File "/home/nicoferfio/rats/RatS/RatS/letterboxd/letterboxd_site.py", line 16, in __init__
    super(Letterboxd, self).__init__(args)
  File "/home/nicoferfio/rats/RatS/RatS/base/base_site.py", line 41, in __init__
    self._init_browser()
  File "/home/nicoferfio/rats/RatS/RatS/base/base_site.py", line 82, in _init_browser
    self.login()
  File "/home/nicoferfio/rats/RatS/RatS/base/base_site.py", line 97, in login
    self._insert_login_credentials()
  File "/home/nicoferfio/rats/RatS/RatS/base/base_site.py", line 142, in _insert_login_credentials
    login_field_user.clear()
  File "/home/nicoferfio/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 93, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "/home/nicoferfio/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 740, in _execute
    return self._parent.execute(command, params)
  File "/home/nicoferfio/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/nicoferfio/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <input id="signin-username" class="field -large" name="username" type="email"> could not be scrolled into view
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:188:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.jsm:298:5
interaction.clearElement@chrome://remote/content/marionette/interaction.js:344:11
clearElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:196:22
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:89:16
-->
```

## Geckodriver log
```
<!--
ATTENTION: default value of option mesa_glthread overridden by environment.
JavaScript warning: https://cdn.js7k.com/ix/talon-1.0.40.js, line 1: WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use REN>[GFX1-]: Couldn't sanitize RENDERER device: D3D12
1660855426820   geckodriver     INFO    Listening on 127.0.0.1:53737
WebDriver BiDi listening on ws://localhost:55849
Read port: 42881
1660855453455   RemoteAgent     WARN    TLS certificate errors will be ignored for this session
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofile8bF3U8/search>Missing chrome or resource URL: resource://gre/modules/UpdateListener.jsm
Missing chrome or resource URL: resource://gre/modules/UpdateListener.sys.mjs
DevTools listening on ws://localhost:55849/devtools/browser/28a7c509-a052-446b-b46f-017acd5b2581
ATTENTION: default value of option mesa_glthread overridden by environment.
JavaScript warning: https://cdn.intergient.com/pageos/1.8.14/videoCard.01fa78e7064a386f48fc.js, line 1: WEBGL_debug_renderer_info is deprecated in Firefox >[GFX1-]: Couldn't sanitize RENDERER device: D3D12
JavaScript warning: https://z.moatads.com/playwireprebidheader597261727146/moatheader.js, line 217: WEBGL_debug_renderer_info is deprecated in Firefox and >[GFX1-]: Couldn't sanitize RENDERER device: D3D12
JavaScript error: https://eus.rubiconproject.com/usync.js, line 4: SecurityError: The operation is insecure.
JavaScript error: https://eus.rubiconproject.com/usync.js, line 4: SecurityError: The operation is insecure.
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://letterboxd.com"
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://letterboxd.com"
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://letterboxd.com"
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://letterboxd.com"
1660855465763   Marionette      WARN    Ignoring event 'DOMContentLoaded' because document has an invalid readyState of 'complete'.
ATTENTION: default value of option mesa_glthread overridden by environment.
JavaScript warning: https://z.moatads.com/playwireprebidheader597261727146/moatheader.js, line 217: WEBGL_debug_renderer_info is deprecated in Firefox and >[GFX1-]: Couldn't sanitize RENDERER device: D3D12
-->
```

**Additional context**
None

**Comment by StegSchreck** [comment]
This might be related to a smaller screensize when using the WSL. Have you tried the `-x` option?

**Comment by nicoferfio** [comment]
I tried that but it is inconsistent. What's weird it's that this error comes up even though login is actually sucessful

![2022-09-03 15-04-55](https://user-images.githubusercontent.com/7853926/188272172-666f19ba-7c9f-4779-88de-c28516e0df6a.gif)

**Comment by StegSchreck** [comment]
I have tried this five times in a row here on my local today, and didn't encounter the same issue.

**Comment by StegSchreck** [comment]
will become obsolete with #306
