### ISSUE TITLE
update to 1.0 gives ModuleNotFoundError: No module named 'pydantic'

### ISSUE THREAD

**Issue by noyse27** [StegSchreck/RatS#213]
hi 

i updated to v1.0. and rats will not start anymore:

 `python3 transfer_ratings.py --source trakt --destination letterboxd &`

results in:

```
Traceback (most recent call last):
  File "transfer_ratings.py", line 10, in <module>
    from RatS.allocine.allocine_ratings_inserter import AlloCineRatingsInserter
  File "/root/RatS/RatS/allocine/allocine_ratings_inserter.py", line 8, in <module>
    from RatS.allocine.allocine_site import AlloCine
  File "/root/RatS/RatS/allocine/allocine_site.py", line 6, in <module>
    from RatS.base.base_site import BaseSite
  File "/root/RatS/RatS/base/base_site.py", line 12, in <module>
    from RatS.base.movie_entity import Site
  File "/root/RatS/RatS/base/movie_entity.py", line 4, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
```
using RatS on debian 10 with python 3

**Comment by StegSchreck** [comment]
Hey @noyse27 
Have you run `pip install -r requirements.txt` àfter upgrading to the new version?

**Comment by noyse27** [comment]
yes i did - without any error message

**Comment by noyse27** [comment]
hmm okay i will try
