### ISSUE TITLE
moviepilot scraping not working

### ISSUE THREAD

**Issue by Rick7221** [StegSchreck/RatS#229]
Hi, i had to login using the -x option, but afterwards the script fails to scrape the content, i get the following error:

```
minty@minty-virtual-machine:~/Desktop/RatS$ python3 transfer_ratings.py --source moviepilot --destination imdb 
===== MoviePilot: performing loginTraceback (most recent call last):
  File "/home/minty/Desktop/RatS/transfer_ratings.py", line 286, in <module>
    main()
  File "/home/minty/Desktop/RatS/transfer_ratings.py", line 98, in main
    execute(args)
  File "/home/minty/Desktop/RatS/transfer_ratings.py", line 179, in execute
    parser: RatingsParser = get_parser_from_arg(site)(args)
  File "/home/minty/Desktop/RatS/RatS/moviepilot/moviepilot_ratings_parser.py", line 15, in __init__
    super(MoviePilotRatingsParser, self).__init__(MoviePilot(args), args)
  File "/home/minty/Desktop/RatS/RatS/moviepilot/moviepilot_site.py", line 13, in __init__
    super(MoviePilot, self).__init__(args)
  File "/home/minty/Desktop/RatS/RatS/base/base_site.py", line 43, in __init__
    self._init_browser()
  File "/home/minty/Desktop/RatS/RatS/base/base_site.py", line 84, in _init_browser
    self.login()
  File "/home/minty/Desktop/RatS/RatS/base/base_site.py", line 100, in login
    self._click_login_button()
  File "/home/minty/Desktop/RatS/RatS/base/base_site.py", line 154, in _click_login_button
    login_button.click()
  File "/home/minty/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/minty/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 410, in _execute
    return self._parent.execute(command, params)
  File "/home/minty/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/home/minty/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="akU5C _385kg _25g6c sc-9397mk-4 bnbwDX" type="submit"> is not clickable at point (360,504) because another element <iframe id="ur-render-target" class="urp-no-hide" name="ur-render-target" src="about:blank"> obscures it
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
ElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:281:5
webdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:160:11
interaction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:119:11
clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:198:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:86:31
```

**Comment by Tekl** [comment]
It seems not to work anymore.

> ===== MoviePilot: Parsing 4 pages with 363 movies in total
Traceback (most recent call last):
  File "~/Downloads/RatS-master/transfer_ratings.py", line 286, in <module>
    main()
  File "~/Downloads/RatS-master/transfer_ratings.py", line 98, in main
    execute(args)
  File "~/Downloads/RatS-master/transfer_ratings.py", line 180, in execute
    movies: List[Movie] = execute_parsing(args, parser)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Downloads/RatS-master/transfer_ratings.py", line 230, in execute_parsing
    movies: List[Movie] = parse_data_from_source(parser)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Downloads/RatS-master/transfer_ratings.py", line 236, in parse_data_from_source
    movies: List[Movie] = parser.parse()
                          ^^^^^^^^^^^^^^
  File "~/Downloads/RatS-master/RatS/base/base_ratings_parser.py", line 40, in parse
    self._parse_ratings()
  File "~/Downloads/RatS-master/RatS/base/base_ratings_parser.py", line 85, in _parse_ratings
    self._parse_movie_listing_page(movie_listing_page)
  File "~/Downloads/RatS-master/RatS/base/base_ratings_parser.py", line 106, in _parse_movie_listing_page
    movie = self._parse_movie_tile(movie_tile)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Downloads/RatS-master/RatS/base/base_ratings_parser.py", line 156, in _parse_movie_tile
    self.parse_movie_details_page(movie)
  File "~/Downloads/RatS-master/RatS/moviepilot/moviepilot_ratings_parser.py", line 68, in parse_movie_details_page
    movie_id = str(re.findall(r"itemId.*:(\d*),", str(json_from_script))[0])
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
