### ISSUE TITLE
Unable to locate element: [id="csv_file"]

### ISSUE THREAD

**Issue by michomuchomacho** [StegSchreck/RatS#23]
Hey!

I finally had some luck with the Ubuntu Bash in W10 (while docker continues to fail).
I don't know what changed but now it parses (trakt) ratings correctly and generates the JSON, but then fails to pass them on:

```
python3 transfer_ratings.py --source trakt --destination tmdb
===== Trakt: Parsing 19 pages with 1134 movies in total
Trakt [#######################################################################################################] 100.0%

===== Trakt: saved 1134 parsed movies to /*/RatS/RatS/exports/20170818090253_Trakt.json
===== TMDB: posting 1134 movies
===== saving movies to CSV
Traceback (most recent call last):
  File "transfer_ratings.py", line 135, in <module>
    main()
  File "transfer_ratings.py", line 58, in main
    execute(args)
  File "transfer_ratings.py", line 110, in execute
    insert_movie_ratings(inserter, movies, type(parser.site).__name__)
  File "transfer_ratings.py", line 131, in insert_movie_ratings
    inserter.insert(movies, source)
  File "/mnt/c/Users/Sara/RatS/RatS/tmdb/tmdb_ratings_inserter.py", line 23, in insert
    self.upload_csv_file()
  File "/mnt/c/Users/Sara/RatS/RatS/tmdb/tmdb_ratings_inserter.py", line 37, in upload_csv_file
    self.site.browser.find_element_by_id('csv_file').send_keys(os.path.join(self.exports_folder, CSV_FILE_NAME))
  File "/home/ubu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/ubu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 791, in find_element
    'value': value})['value']
  File "/home/ubu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/home/ubu/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="csv_file"]
```

Thanks for your efforts, I hope this can help you!

**Comment by StegSchreck** [comment]
Ok, that's when he tries to upload the CSV to TMDB. He can't find the file upload input field on the page.
I will have a look at this.

**Comment by michomuchomacho** [comment]
I could do it manually with the generated file, so up until then it worked.
I think it could be due to the manual TMDB upload doesn't work properly: it
actually uploaded the ratings, but the page showed an error page.

Great news, anyway! :D

2017-08-18 13:13 GMT+02:00 Sebastian Schreck <notifications@github.com>:

**Comment by StegSchreck** [comment]
There is a bug in Firefox 55 currently, which caused uploading files to fail.
https://github.com/mozilla/geckodriver/issues/858#issuecomment-322512336

I  applied a workaround
