### ISSUE TITLE
Fail importing from FilmAffinity

### ISSUE THREAD

**Issue by fergusreiggracia** [StegSchreck/RatS#271]
**Describe the bug**
Fail importing from FilmAffinity to IMDB

**To Reproduce**
docker run -it -v '/mnt/disco/Descargas/imdb/.RatS.cfg':/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source FilmAffinity --destination IMDB

**Expected behavior**
Copy data from FilmAffinity to IMDB

**Desktop (please complete the following information):**
- Version: Last docker image
- Platform OS: Linux
- Firefox version: --
- Geckodriver version: --
- Python version: --
- PIP version: --
- Running in a virtualenv?: yes
- Running in Docker?: yes
- Executed command: docker run -it -v '/mnt/disco/Descargas/imdb/.RatS.cfg':/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source FilmAffinity --destination IMDB

## Stacktrace
Error and stacktrace produced by the script in the console.
===== FilmAffinity: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 227, in <module>
    main()
  File "transfer_ratings.py", line 79, in main
    execute(args)
  File "transfer_ratings.py", line 127, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/RatS/RatS/filmaffinity/filmaffinity_ratings_parser.py", line 11, in __init__
    super(FilmAffinityRatingsParser, self).__init__(FilmAffinity(args), args)
  File "/RatS/RatS/filmaffinity/filmaffinity_site.py", line 12, in __init__
    super(FilmAffinity, self).__init__(args)
  File "/RatS/RatS/base/base_site.py", line 35, in __init__
    self._init_browser()
  File "/RatS/RatS/base/base_site.py", line 68, in _init_browser
    self.login()
  File "/RatS/RatS/base/base_site.py", line 83, in login
    self._insert_login_credentials()
  File "/RatS/RatS/base/base_site.py", line 121, in _insert_login_credentials
    login_field_user.send_keys(self.USERNAME)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <input name="username" type="text"> is not reachable by keyboard

**Comment by StegSchreck** [comment]
The problem seems to be the bot protection :/
![image](https://github.com/StegSchreck/RatS/assets/9078002/b3408ae2-b182-4535-95dc-7d40d1092cdc)
