### ISSUE TITLE
Can't perform login to IMDB

### ISSUE THREAD

**Issue by Rootzpower** [StegSchreck/RatS#41]
Cant export trakt to imdb

## System
* Version: Latest commit 246ad94 4 days ago
* Platform: Ubuntu 17.10
* Firefox version: 58.0.1
* Geckdrover version: geckodriver 0.19.1
* Python version: Python 3.6.3
* PIP version: pip 9.0.1
* Running in a virtualenv?: yes
* Running in Docker?: no
* Executed command: python3 transfer_ratings.py --source trakt --destination imdb --file 20180129140242_Trakt.json -v

## Stacktrace
```
python3 transfer_ratings.py --source trakt --destination imdb --file 20180129140242_Trakt.json -v
===== Trakt: performing login
===== loaded 586 movies from /home/rootz/RatS/RatS/exports/20180129140242_Trakt.json
===== IMDB: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 158, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 123, in execute
    inserter = get_inserter_from_arg(dest)(args)
  File "/home/rootz/RatS/RatS/imdb/imdb_ratings_inserter.py", line 14, in __init__
    super(IMDBRatingsInserter, self).__init__(IMDB(args), args)
  File "/home/rootz/RatS/RatS/imdb/imdb_site.py", line 15, in __init__
    super(IMDB, self).__init__(args)
  File "/home/rootz/RatS/RatS/base/base_site.py", line 35, in __init__
    self._init_browser()
  File "/home/rootz/RatS/RatS/base/base_site.py", line 98, in _init_browser
    self.login()
  File "/home/rootz/RatS/RatS/base/base_site.py", line 110, in login
    self._click_login_button()
  File "/home/rootz/RatS/RatS/base/base_site.py", line 142, in _click_login_button
    login_button.click()
  File "/home/rootz/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/rootz/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/home/rootz/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/home/rootz/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <input id="audio-captcha-play-pause-button" class="a-button-input" type="submit"> could not be scrolled into view
```

## Geckodriver log
```
<!--
There is a {TIMESTAMP}_geckdrover.log file. Most of the time, this is not needed.
-->
```

**Comment by StegSchreck** [comment]
Hey @Rootzpower.
I updated the selector for the login button. This should work now.

**Comment by Rootzpower** [comment]
===== Trakt: performing login
===== loaded 586 movies from /home/rootz/RatS/RatS/exports/20180129140242_Trakt.json
===== IMDB: performing login
ERROR: Login to IMDB failed.

===== ABORTING =====
There seems to be a Captcha challenge present for the login. Please try again later.

**Comment by StegSchreck** [comment]
Yeah, I experienced that too. I thought it was a local problem to me because of extensive testing and hoped it would not happen to you. The script can't handle captchas of course. This will need some manual handling. Could you please try again tomorrow and see if IMDB resets to normal login behavior after some time or if the issue persists?

**Comment by Rootzpower** [comment]
I´ve successfully login now.
The script are running and posting.
I hope run to end

**Comment by StegSchreck** [comment]
Thank you for the update.

**Comment by hairyhippy** [comment]
This issue still persists for me.  I will try again tomorrow.
