### ISSUE TITLE
Can't perform login to PLEX

### ISSUE THREAD

**Issue by 5u4573** [StegSchreck/RatS#42]
Hello again, I'm trying to use Rats to transfer data from PLEX to TMDB but when executing the command

python3 transfer_ratings.py --source plex --destination tmdb

give me the following error

AttributeError: 'Plex' object has no attribute 'browser'
.

## System
* Version: Latest
* Platform: Linux Ubuntu 16.04 (64 bits)
* Firefox version: 58.0.1 (64-bits) 
* Geckdrover version: geckodriver 0.19.1
* Python version: Python 2.7.12
* Python3 version: Python 3.5.2
* PIP version: pip 9.0.1 
* Running in a virtualenv?: no 
* Running in Docker?: no 
* Executed command: python3 transfer_ratings.py -s plex -d tmdb

## Stacktrace
```
===== Plex: determine movie sectionTraceback (most recent call last):
  File "transfer_ratings.py", line 158, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 110, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/home/miguel/RatS/RatS/plex/plex_ratings_parser.py", line 10, in __init__
    super(PlexRatingsParser, self).__init__(Plex(args), args)
  File "/home/miguel/RatS/RatS/plex/plex_site.py", line 15, in __init__
    super(Plex, self).__init__(args)
  File "/home/miguel/RatS/RatS/base/base_site.py", line 33, in __init__
    self._parse_configuration()
  File "/home/miguel/RatS/RatS/plex/plex_site.py", line 20, in _parse_configuration
    self.MOVIE_SECTION_ID = self._determine_movies_section_id()
  File "/home/miguel/RatS/RatS/plex/plex_site.py", line 32, in _determine_movies_section_id
    self.browser.get('http://{base_url}/library/sections'.format(base_url=self.BASE_URL))
AttributeError: 'Plex' object has no attribute 'browser'
```

**Comment by StegSchreck** [comment]
Hey @5u4573.
In order to optimize my code I introduced this bug some time ago. It was trying to interact with the site (for some configuration values) before the connection was even initialized. I just fixed this. Hope this works for you now.
