### ISSUE TITLE
Problem with UTF8 from imdb to trakt

### ISSUE THREAD

**Issue by puchrojo** [StegSchreck/RatS#47]
I follow the instruction and the program start. But I geht

## System
* Version: commit 6314f86292116fa802745e367e3ffef069cb0d6b
* Platform: Ubuntu 18.04 LTS 
* Firefox version: 59.0.2 (64-Bit)
* Geckdrover version: 0.20.1
* Python version: 2.7.15rc1
* PIP version: pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
* Running in a virtualenv?:  no
* Running in Docker?: no
* Executed command: python3 transfer_ratings.py --source IMDB  --destination trakt

## Stacktrace
===== IMDB: CSV downloaded to /home/puchrojo/repositories/RatS/RatS/exports/20180510211929_IMDB.csv
===== getting movies from CSV
Traceback (most recent call last):
  File "transfer_ratings.py", line 168, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 111, in execute
    movies = execute_parsing(args, parser)
  File "transfer_ratings.py", line 133, in execute_parsing
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 138, in parse_data_from_source
    movies = parser.parse()
  File "/home/puchrojo/repositories/RatS/RatS/base/base_ratings_parser.py", line 30, in parse
    self._parse_ratings()
  File "/home/puchrojo/repositories/RatS/RatS/imdb/imdb_ratings_parser.py", line 16, in _parse_ratings
    self.movies = file_impex.load_movies_from_csv(os.path.join(self.exports_folder, self.csv_filename))
  File "/home/puchrojo/repositories/RatS/RatS/utils/file_impex.py", line 44, in load_movies_from_csv
    next(reader, None)  # ignore csv header
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 4999: invalid start byte

-----------------------------
My rating list on IMDB ist public: https://www.imdb.com/user/ur5211117/ratings?ref_=uspf_rt
 
Vielen Dank!

**Comment by Rootzpower** [comment]
same problem here.
Cant export or transfer imdb->trakt for exemple
I attach cvs file from imdb
python3 transfer_ratings.py --source imdb
===== IMDB: CSV downloaded to /home/rootz/RatS/RatS/exports/20180514173856_IMDB.csv
===== getting movies from CSV
Traceback (most recent call last):
  File "transfer_ratings.py", line 168, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 111, in execute
    movies = execute_parsing(args, parser)
  File "transfer_ratings.py", line 133, in execute_parsing
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 138, in parse_data_from_source
    movies = parser.parse()
  File "/home/rootz/RatS/RatS/base/base_ratings_parser.py", line 30, in parse
    self._parse_ratings()
  File "/home/rootz/RatS/RatS/imdb/imdb_ratings_parser.py", line 16, in _parse_ratings
    self.movies = file_impex.load_movies_from_csv(os.path.join(self.exports_folder, self.csv_filename))
  File "/home/rootz/RatS/RatS/utils/file_impex.py", line 44, in load_movies_from_csv
    next(reader, None)  # ignore csv header
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 1048: invalid start byte
rootz@Ubuntu-VirtualBox:~/RatS$ 

``
[20180514173856_IMDB.zip](https://github.com/StegSchreck/RatS/files/2001752/20180514173856_IMDB.zip)

**Comment by StegSchreck** [comment]
Thank you @Rootzpower for the provided data, that helped a lot. 
It seems to me that IMDB changed the output structure and encoding of the csv export. I adapted my script accordingly.
I hope it works for you again now.

**Comment by Rootzpower** [comment]
Thanks for the fix.
It works again! :)
