### ISSUE TITLE
tmdb login button obscured

### ISSUE THREAD

**Issue by jonasAhnstrom** [StegSchreck/RatS#62]
**Describe the bug**
Failure to use tmdb as destination or source.

**To Reproduce**
1. Run script with source imdb and destination tmdb
2. See error

**Expected behavior**
Script to finish without error.

**Desktop (please complete the following information):**
- Version: commit hash b002a58bc0fcab8a7301c3b429c163a7c9b5a001
- Platform OS: KDE neon 5.12
- Firefox version: 59.0.2
- Geckdrover version: 0.23.0
- Python version: 3.5.2
- PIP version: 9.0.3
- Running in a virtualenv?: no
- Running in Docker?: no
- Executed command: python3 transfer_ratings.py --source imdb --destination tmdb

## Stacktrace
```
===== TMDB: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 168, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 110, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/home/jonas/RatS/RatS/tmdb/tmdb_ratings_parser.py", line 9, in __init__
    super(TMDBRatingsParser, self).__init__(TMDB(args), args)
  File "/home/jonas/RatS/RatS/tmdb/tmdb_site.py", line 10, in __init__
    super(TMDB, self).__init__(args)
  File "/home/jonas/RatS/RatS/base/base_site.py", line 32, in __init__
    self._init_browser()
  File "/home/jonas/RatS/RatS/base/base_site.py", line 60, in _init_browser
    self.login()
  File "/home/jonas/RatS/RatS/base/base_site.py", line 73, in login
    self._click_login_button()
  File "/home/jonas/RatS/RatS/base/base_site.py", line 111, in _click_login_button
    login_button.click()
  File "/home/jonas/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/jonas/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/jonas/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/jonas/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input class="k-button k-primary" type="submit"> is not clickable at point (32.5,498.6000061035156) because another element <a href="https://www.tivo.com/legal/cookies"> obscures it
```

## Geckodriver log
```
1539315225356	addons.xpi	WARN	disabling legacy extension {03cb16aa-4675-11e5-b233-213b1d5d46b0}
1539315225356	addons.xpi	WARN	disabling legacy extension {03cb16aa-4675-11e5-b233-213b1d5d46b0}
1539315225356	addons.xpi	WARN	disabling legacy extension {03cb16aa-4675-11e5-b233-213b1d5d46b0}
1539315225526	addons.xpi	WARN	disabling legacy extension {03cb16aa-4675-11e5-b233-213b1d5d46b0}
1539315225528	addons.xpi	WARN	disabling legacy extension {03cb16aa-4675-11e5-b233-213b1d5d46b0}
1539315226672	Marionette	WARN	TLS certificate errors will be ignored for this session
ATTENTION: default value of option force_s3tc_enable overridden by environment.
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1539315251038	addons.xpi	WARN	disabling legacy extension {03cb16aa-4675-11e5-b233-213b1d5d46b0}
1539315251038	addons.xpi	WARN	disabling legacy extension {03cb16aa-4675-11e5-b233-213b1d5d46b0}
1539315251038	addons.xpi	WARN	disabling legacy extension {03cb16aa-4675-11e5-b233-213b1d5d46b0}
1539315251208	addons.xpi	WARN	disabling legacy extension {03cb16aa-4675-11e5-b233-213b1d5d46b0}
1539315251210	addons.xpi	WARN	disabling legacy extension {03cb16aa-4675-11e5-b233-213b1d5d46b0}
1539315252278	Marionette	WARN	TLS certificate errors will be ignored for this session

(/usr/lib/firefox/firefox:9985): dconf-WARNING **: Unable to open /var/lib/snapd/desktop/dconf/profile/user: Permission denied
```

**Additional context**
None.

**Comment by StegSchreck** [comment]
Hey @jonasAhnstrom.
Thank you for reporting this issue. I moved the handling of the cookie banner to an earlier time, so this should not prevent the login anymore.

Best regards.
