### ISSUE TITLE
Error in pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by renan905** [StegSchreck/RatS#78]
#**Describe the bug**
I'm getting two erros in the export/import process.
First one is when a try to install the requirements "pip3 install -r requirements.txt", i getting a error in "python.py egg_info".
The second one is when a try to run the script. I get the " ModuleNotFoundError: No module named 'selenium' ", probably because the first erro.

**To Reproduce**
1. Run pip3 install -r requirements.txt
2. See error

3. Run python3 transfer_ratings.py --source trakt --destination imdb

- Platform OS: Mint Tara
- Firefox version: 61.0.1
- Geckdrover version: geckodriver v0.23.0
- Python version: python 3.6.5
- PIP version: pip --version 9.0.1
- Running in a virtualenv?: yes
- Running in Docker?: no

## Stacktrace
```
Error 1
pip3 install -r requirements.txt
Collecting beautifulsoup4==4.6.3 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/21/0a/47fdf541c97fd9b6a610cb5fd518175308a7cc60569962e776ac52420387/beautifulsoup4-4.6.3-py3-none-any.whl
Collecting configparser==3.5.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-w__5zd5s/configparser/


Error 2
python3 transfer_ratings.py --source trakt --destination imdb
Traceback (most recent call last):
  File "transfer_ratings.py", line 8, in <module>
    from RatS.criticker.criticker_ratings_inserter import CritickerRatingsInserter
  File "/home/renan/RatS/RatS/criticker/criticker_ratings_inserter.py", line 5, in <module>
    from selenium.common.exceptions import NoSuchElementException
ModuleNotFoundError: No module named 'selenium'

```

**Comment by renan905** [comment]
@StegSchreck 
Now it's working fine, i have to install the `setuptools` and also reinstall `Xvfb`.
Thanks
