### ISSUE TITLE
Error on conversion Trakt -> IMDb

### ISSUE THREAD

**Issue by bergercookie** [StegSchreck/RatS#79]
I'm trying to transfer my ratings from Trakt to IMDb. First time I run the `transfer_ratings.py script I got a runtime error when posting the ratings to IMDb. However, the second time it worked as expected.

**To Reproduce**

* setup RatS as per instructions and
* install the geckodriver systemwide using the `InstallGeckodriver.sh` script
* Run transfer_rating.py script using python3:

    `python3 transfer_ratings.py --source trakt --destination imdb`

**Expected behavior**

To actually transfer my ratings.

**Desktop (please complete the following information):**
- Version: 88d9eef
- Platform OS: Ubuntu 18.04
- Firefox version: 62.0a1 (2018-05-11)
- Geckdrover version: geckodriver 0.23.0
- Python version: Python 3.6.7
- PIP version: pip 9.0.1
- Running in a virtualenv?: no
- Running in Docker?: no
- Executed command: `python3 transfer_ratings.py --source trakt --destination imdb`

## Stacktrace
```
~/RatS$ python3 transfer_ratings.py --source trakt --destination imdb
===== Trakt: Parsing 2 pages with 115 movies in total
100% (115 of 115) |##########################################################################################################################################################| Elapsed Time: 0:05:15 Time:  0:05:15
===== Trakt: saved 115 parsed movies to /home/berger/RatS/RatS/exports/20190105142259_Trakt.json
===== IMDB: posting 115 movies
Traceback (most recent call last):
  File "transfer_ratings.py", line 172, in <module>
    main()
  File "transfer_ratings.py", line 69, in main
    execute(args)
  File "transfer_ratings.py", line 116, in execute
    execute_inserting(args, movies, parser)
  File "transfer_ratings.py", line 127, in execute_inserting
    insert_movie_ratings(inserter, movies, type(parser.site).__name__)
  File "transfer_ratings.py", line 168, in insert_movie_ratings
    inserter.insert(movies, source)
  File "/home/berger/RatS/RatS/base/base_ratings_inserter.py", line 44, in insert
    self._post_movie_rating(movie[source.lower()]['my_rating'])
  File "/home/berger/RatS/RatS/base/base_ratings_inserter.py", line 141, in _post_movie_rating
    self._click_rating(my_rating)
  File "/home/berger/RatS/RatS/imdb/imdb_ratings_inserter.py", line 49, in _click_rating
    .move_to_element(stars[star_index]).click(stars[star_index])\
  File "/home/berger/.local/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/home/berger/.local/lib/python3.6/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/home/berger/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/berger/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: rect is undefined
```

Unfortunately I accidentally removed the Gecko driver log file.

Since it worked the 2nd time, i'm not too fussed about it, but I'm posting in case you want to deal with such an error.

**Comment by samtihen** [comment]
Same issue here. In my case, it is from icheckmovies to imdb. I'm using the docker container version. I have not been able to get it to fully work, it fails after about 5-10% progress.

**Comment by StegSchreck** [comment]
I had several runs over the last couple of days and didn't encounter this error. If it comes up again, please reopen this issue and attach a Geckodriver logfile and the json the script tries to insert to imdb.
