### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="sncmp-container"]

### ISSUE THREAD

**Issue by zotoro** [StegSchreck/RatS#98]
I'm having a problem where the script is throwing a strange error after logging into the destination website. I've followed the instructions provided exactly and I've also tried googling the error code, but nothing comes up when I search for "sncmp-container." Hopefully you can provide some insight on what the problem is, as I am stumped. I've pasted the output of the script below.

I'm trying to run this script on Linux Mint x64 running in VirtualBox if that matters.

I have also updated firefox, Xvfb, and geckodriver multiple times along with all of the dependencies. Nothing has worked so far.

> user@user-VirtualBox:~/RatS-0.12$ python3 transfer_ratings.py -s movielens -d trakt
===== Movielens: CSV downloaded to /home/user/RatS-0.12/RatS/exports/20191107214301_Movielens.csv
===== getting movies from CSV
===== Movielens: saved 642 parsed movies to /home/user/RatS-0.12/RatS/exports/20191107214301_Movielens.json
===== Trakt: performing loginTraceback (most recent call last):
  File "transfer_ratings.py", line 180, in <module>
    main()
  File "transfer_ratings.py", line 77, in main
    execute(args)
  File "transfer_ratings.py", line 124, in execute
    execute_inserting(args, movies, parser)
  File "transfer_ratings.py", line 134, in execute_inserting
    inserter = get_inserter_from_arg(dest)(args)
  File "/home/user/RatS-0.12/RatS/trakt/trakt_ratings_inserter.py", line 12, in __init__
    super(TraktRatingsInserter, self).__init__(Trakt(args), args)
  File "/home/user/RatS-0.12/RatS/trakt/trakt_site.py", line 13, in __init__
    self._handle_privacy_notice_if_present()
  File "/home/user/RatS-0.12/RatS/trakt/trakt_site.py", line 19, in _handle_privacy_notice_if_present
    privacy_notice = self.browser.find_element_by_id('sncmp-container')
  File "/home/user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/user/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="sncmp-container"]`

**EDIT**: I seem to have solved the problem by editing line 13 of trakt_site.py and turned the line into a comment so that the function to find the element "sncmp-container" is never called and the error is never thrown. This isn't a real fix though, so it would probably be worth figuring out what is causing the element to not be found in the first place.

**Comment by StegSchreck** [comment]
Hello @zotoro.
Thank you for submitting this. I changed the according place in the code to be more resilient, if the cookie notice is not displayed.
